name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://hackatime.hackclub.com/api/hackatime/v1
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          LANG_COUNT : 3
          COMMITTER_NAME: ReadMe-BOT # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: Sanchit Lamba # optional
          AUTHOR_EMAIL: mail@sanchit.cc # optional
